### ISSUE TITLE
Order of including omp.h matters for compilation

### ISSUE THREAD

**Issue by kannon92** [solomonik/ctf#27] opened 2016-10-04 14:49 UTC
Hello,  

I found an annoying compilation error if I include omp.h after ctf.hpp.  I am running with gcc-4.9, MVAPICH2, and cyclops.  Here is a simple program to reproduce the problem.  This problem goes away if omp.h is included before ctf.hpp.  

    #include <stdio.h>
    #include <stdlib.h>
    #include <mpi.h>
    #include <ctf.hpp>
    #include <omp.h>
    //using namespace CTF;
    int main (int argc, char **argv)
    {
     int rank, size;
     MPI_Init (&argc, &argv);
     long n = 400 * 400; 
     long m = 333;
     int nthread = omp_get_max_threads();
     CTF::World dw(MPI_COMM_WORLD);
     CTF::Matrix<double> A_MN(m, n, dw);
     CTF::Matrix<double> J_12(m, m, dw);
     CTF::Matrix<double> Q_MN(m, n, dw);
     A_MN.fill_random(0, 1);
     J_12.fill_random(0, 1);
     Q_MN["Qij"] = A_MN["Aij"] * J_12["AQ"];
      printf("\n Q_NORM: %8.8f", Q_MN.norm2());
      //  long m = 333;
         MPI_Finalize();
       return 0;
     }

**Comment by kannon92** [comment] 2016-10-04 14:57
So I have no idea if this breaks anything, but if you include omp.h in ctf.hpp before any ctf specific headers, the compilation bug goes away.

**Comment by devinamatthews** [comment] 2016-10-04 14:59
Could you please post the compiler message(s)? I have a feeling it might 
have to do with a conflicting implicit declaration.

**Comment by kannon92** [comment] 2016-10-04 15:19
mock_ctf.cc: In function ‘int main(int, char**)’:
    mock_ctf.cc:18:37: error: ‘omp_get_max_threads’ was not declared in this scope
       int nthread = omp_get_max_threads();
                                     ^
     mock_ctf.cc:18:37: note: suggested alternative:
     In file included from      /home/kannon/src/ctf/include/../src/interface/../contraction/../shared/util.h:132:0,
                 from /home/kannon/src/ctf/include/../src/interface/../contraction/ctr_tsr.h:7,
                 from /home/kannon/src/ctf/include/../src/interface/../contraction/contraction.h:5,
                 from /home/kannon/src/ctf/include/../src/interface/functions.h:6,
                 from /home/kannon/src/ctf/include/../src/interface/tensor.h:4,
                 from /home/kannon/src/ctf/include/ctf.hpp:20,
                 from /home/kannon/src/ctf/Build/include/ctf.hpp:1,
                 from mock_ctf.cc:4:
     /usr/lib64/gcc/x86_64-suse-linux/4.9/include/omp.h:73:12: note:   ‘CTF_int::omp_get_max_threads’
     extern int omp_get_max_threads (void) __GOMP_NOTHROW;

**Comment by devinamatthews** [comment] 2016-10-04 15:23
It looks like omp.h is being #included inside the CTF_int namespace 
(src/shared/util.h:132). Should be an easy fix, although I'm not 
actually sure how it works at all as it is.

**Comment by jeffhammond** [comment] 2016-10-04 15:25
`mock_ctf.cc` is not part of the CTF repo.

In any case, it seems that `extern "C" { }` might be required, or some other fix for the namespace issue.

**Comment by jeffhammond** [comment] 2016-10-04 15:28
`src/shared/util.h` has a lot of issues.  `omp.h` is not the only include that needs to happen outside of the `CTF_int` namespace...

**Comment by kannon92** [comment] 2016-10-04 15:56
Thank you for the changes.  mock_ctf.cc was what I called the test program I used.

**Comment by solomonik** [comment] 2016-10-04 16:32
Hi Kevin,

Thanks for the bug report.  I just pushed a fix to master.  As Jeff and Devin pointed out the omp.h include should not have been in the namespace CTF_int {} block.  Moreover src/shared/util.h should not even be included from any interface files and is meant to be internal.  I made changes to fix both.

Also, separately, you should initialize the random seed generator srand48(...) to something dependent on processor rank, before calling fill_random on CTF tensors.  CTF does not perform any seeding itself, since its not evident how to do so robustly while preserving reproducibility.

Best regards,
Edgar

**Closed by solomonik** 2016-10-04 16:32 UTC

**Comment by kannon92** [comment] 2016-10-04 16:49
Thank you for your help.

**Comment by jeffhammond** [comment] 2016-10-04 17:28
Regarding `srand48`, C++11 has great features for [RNG](http://en.cppreference.com/w/cpp/numeric/random)...

**Comment by jeffhammond** [comment] 2016-10-04 17:29
If C++11 can't be required, [Boost](http://www.boost.org/doc/libs/1_61_0/doc/html/boost_random.html) works.

I know I am a big hypocrite for recommending C++11 and Boost now, given my position in ~2012, but C++ compilers have had 4 years to stop sucking.

**Comment by solomonik** [comment] 2016-10-04 17:50
(Sorry for the off-topic discussion.)  CTF currently requires C++11.  I am happy to learn C++11 has more robust support for RNGs and will keep that in mind.  However, I am not sure they provide a solution to the underlying problem with parallel RNG generation for a library like CTF.  One can just generate non-deterministically, but determinism is extremely valuable for reproducible testing.  However, then one has to insure that different processors get a different seed and different tensors get a different seed, and it becomes not so clear how to do that (e.g. on a CTF instance basis or via global counter) and how to let the user control it.  

I guess the right solution might be to have fill_random_nondeterministic and fill_random_preseeded.  Then it remains to figure out whether fill_random_preseeded should have all processor ranks with the same seed or with a different seed, and how to handle the former, which is where C++11 RNGs may help.  And what fill_random should do for backwards comp.
